root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

format: gitbook

plugins:
  - favicon
  - katex
  - mathjax

pluginsConfig:
  favicon:
    shortcut: .gitbook/assets/favicon.ico
    apple-touch-icon: .gitbook/assets/favicon.ico
  mathjax:
    forceSVG: true
  katex:
    delimiters:
      - left: "$$"
        right: "$$"
        display: true
      - left: "$"
        right: "$"
        display: false
