name: Run dapp tests

on:
  #pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build --filter dapp

  test-app:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.10.0'

      - name: Run jest tests
        run: yarn test:dapp

