name: Test .NET app

on:
  pull_request:
    paths:
      - 'packages/dotnet-sdk/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

jobs:
  test-dotnet-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['8.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to folder
        run: pwd

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore packages/dotnet-sdk

      - name: Verify dependencies
        run: dotnet build packages/dotnet-sdk

      - name: Run tests with coverage
        run: dotnet test packages/dotnet-sdk --no-restore